{{- if not .Values.credentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pds.fullname" . }}
  labels:
    {{- include "pds.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ required "credentials.jwtSecret is required" .Values.credentials.jwtSecret | quote }}
  admin-password: {{ required "credentials.adminPassword is required" .Values.credentials.adminPassword | quote }}
  plc-rotation-key: {{ required "credentials.plcRotationKey is required" .Values.credentials.plcRotationKey | quote }}
  blobstore-access-key-id: {{ required "credentials.blobstoreAccessKeyId is required" .Values.credentials.blobstoreAccessKeyId | quote }}
  blobstore-secret-access-key: {{ required "credentials.blobstoreSecretAccessKey is required" .Values.credentials.blobstoreSecretAccessKey | quote }}
{{- end }}
