#!/usr/bin/env bash
set -euo pipefail

OUT="my-secrets.yaml"

if [[ -f "$OUT" ]]; then
  echo "$OUT already exists — skipping. Delete it and re-run to regenerate secrets." >&2
  exit 0
fi

# secp256k1 private key used to sign did:plc operations for user accounts.
# 32 random bytes expressed as 64 hex characters. A value in [1, n-1] is
# required; the probability of exceeding the curve order is negligible (~2^-128).
PLC_ROTATION_KEY=$(openssl rand -hex 32)

cat > "$OUT" <<EOF
# my-secrets.yaml — generated by scripts/gen-secrets.sh
# Do not commit this file. It is listed in .gitignore.
#
# blobstoreAccessKeyId and blobstoreSecretAccessKey come from MicroCeph:
#   sudo radosgw-admin user create --uid=pds --display-name=pds
# Copy access_key and secret_key from the output into the fields below.
#
# emailSmtpUrl embeds your Resend API key; emailFromAddress must match a
# domain verified in the Resend dashboard. See README.md for setup steps.
credentials:
  jwtSecret: "$(openssl rand -hex 32)"
  adminPassword: "$(openssl rand -hex 16)"
  plcRotationKey: "${PLC_ROTATION_KEY}"
  blobstoreAccessKeyId: ""
  blobstoreSecretAccessKey: ""
  emailSmtpUrl: ""
config:
  emailFromAddress: ""
EOF

echo "Generated $OUT."
echo ""
echo "Fill in blobstoreAccessKeyId and blobstoreSecretAccessKey from:"
echo "  sudo radosgw-admin user create --uid=pds --display-name=pds"
echo ""
echo "Fill in credentials.emailSmtpUrl and config.emailFromAddress (see README.md, Email (Resend))."
echo ""
echo "You can install from source with:"
echo "  helm upgrade --install pds ./charts/pds --namespace pds --create-namespace \\"
echo "    --set config.hostname=yourdomain.com \\"
echo "    --set blobstore.endpoint=http://<node-ip>:7480 \\"
echo "    --set cloudflare.enabled=true \\"
echo "    --set cloudflare.tunnelId=<tunnel-id> \\"
echo "    --set cloudflare.hostname=yourdomain.com \\"
echo "    -f $OUT"
